In [4]:
from numpy import *


1. 生成一个4*4的随机数组

In [ ]:
random.rand(4,4)

2. 矩阵操作   
    - mat() 函数可以将数组转换成矩阵
    - 使用 .I操作符实现矩阵的求逆运算
    - eye(4) 是生成4*4的矩阵

In [20]:
randMat = mat(random.rand(4,4))
print (randMat)
randMat.I
randMat*randMat.I
#取得误差值
myEye = randMat*randMat.I
print(myEye -eye(4))
randMat.I

[[0.59833574 0.91290174 0.32741299 0.48390082]
 [0.0974957  0.55096241 0.9111838  0.78204525]
 [0.53028188 0.80836919 0.28647481 0.84440717]
 [0.10663058 0.33822578 0.95708493 0.4003509 ]]
[[ 2.22044605e-16  0.00000000e+00 -4.44089210e-16  4.44089210e-16]
 [-1.11022302e-16 -2.22044605e-16  2.77555756e-16  0.00000000e+00]
 [-2.22044605e-16  0.00000000e+00 -2.22044605e-16  8.88178420e-16]
 [ 1.11022302e-16 -2.22044605e-16  5.55111512e-17  2.22044605e-16]]


matrix([[-2.13976933e+00, -6.04677753e+00,  4.37015448e+00,
          5.18070516e+00],
        [ 3.68865070e+00,  4.26181974e+00, -4.12420773e+00,
         -4.08483252e+00],
        [-1.74948642e-01, -8.32314659e-01, -3.30324207e-02,
          1.90697292e+00],
        [-2.12811111e+00, -2.25062018e-04,  2.39923552e+00,
          1.00887233e-02]])